from http import HTTPStatus


URL_MAX_LENGTH = 512
SHORT_ID_MAX_LENGTH = 16
SHORT_ID_REGEX = r'^[a-zA-Z0-9_]+$'
STATUS_OK = HTTPStatus.OK
NOT_FOUND = HTTPStatus.NOT_FOUND
BAD_REQUEST = HTTPStatus.BAD_REQUEST
CREATED = HTTPStatus.CREATED
SERVER_ERROR = HTTPStatus.INTERNAL_SERVER_ERROR
